services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-order-service
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
    ports:
      - "3317:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql
